// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: '/api',
  envName: 'PROD',
  middleware: '',
  apiEndPoint: 'https://wndo.net:8090/api/app',
  mobileAppIosUrl: 'https://apps.apple.com/eg/app/wndo/id1588238250',
  mobileAppGooglePlayUrl: 'https://play.google.com/store/apps/details?id=com.window.wndo',

};

