// This file can be replaced during build by using the `fileReplacements` array.
// `ng build ---prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  serverUrl: '/api',
  mobileAppIosUrl: 'https://apps.apple.com/eg/app/wndo/id1588238250',
  mobileAppGooglePlayUrl: 'https://play.google.com/store/apps/details?id=com.window.wndo',
  envName: 'DEV',
  middleware: '',
  apiEndPoint: 'https://wndo.net:8090/api/app',
};

/*
 * In development mode, to ignore zone related error stack frames such as
 * `zone.run`, `zoneDelegate.invokeTask` for easier debugging, you can
 * import the following file, but please comment it out in production mode
 * because it will have performance impact when throw error
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.
